### ISSUE TITLE
Allow specific version to be set

### ISSUE THREAD

**Issue by mbround18** [kpenfound/valheim-server#2]
Hey this is amazing work! I love it!! 

I did have one suggestion! For your variable on the image name either break this into two vars or a map with the image and version being separate. So that people can install a stable version just with a version flag :) 

https://github.com/kpenfound/valheim-server/blob/6a2a671f2c9072a1223b80310670fe77f59b1210/variables.tf#L31

Also absolutely excellent job here!

**Comment by kpenfound** [comment]
Yes great suggestion, I will make that change!

**Comment by kpenfound** [comment]
Fixed in https://github.com/kpenfound/valheim-server/commit/a2c96ede0d6c07f8ddcd14a82c7c1a8876c2b5c8 !
